apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafkaclient-deply
  labels:
    app: kafkaclient
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kafkaclient
  template:
    metadata:
      labels:
        app: kafkaclient
    spec:
      containers:
        - name: kafkaclient
          image: allfordev/kafkaclient
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: kafkaclient-service
spec:
  selector:
    app: kafkaclient
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: kafkaclient-service-ext
spec:
  selector:
    app: kafkaclient
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 32002